import { Product } from "./types";

export const initialProducts: Product[] = [
  {
    id: "ip17pm-256-nt",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    model: "iPhone 17 Pro Max",
    storage: "256GB",
    color: "Natural Titanium",
    condition: "New",
    price: 5499,
    image: "",
    description: "The most powerful iPhone ever. Titanium design, A19 Pro chip, and pro camera system.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ip17pm-512-bt",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    model: "iPhone 17 Pro Max",
    storage: "512GB",
    color: "Black Titanium",
    condition: "New",
    price: 6199,
    image: "",
    description: "The most powerful iPhone ever. Titanium design, A19 Pro chip, and pro camera system.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ip17pm-1tb-wt",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    model: "iPhone 17 Pro Max",
    storage: "1TB",
    color: "White Titanium",
    condition: "New",
    price: 7099,
    image: "",
    description: "Maximum storage. Maximum performance. The pinnacle of iPhone.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ip16p-256-db",
    name: "iPhone 16 Pro",
    brand: "Apple",
    model: "iPhone 16 Pro",
    storage: "256GB",
    color: "Desert Titanium",
    condition: "New",
    price: 4299,
    image: "",
    description: "A18 Pro chip, titanium design, and the best camera in iPhone history.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ip15-128-used",
    name: "iPhone 15",
    brand: "Apple",
    model: "iPhone 15",
    storage: "128GB",
    color: "Pink",
    condition: "Used",
    price: 2199,
    image: "",
    description: "Excellent condition. Dynamic Island, 48MP camera, USB-C.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ss26u-256-tg",
    name: "Galaxy S26 Ultra",
    brand: "Samsung",
    model: "Galaxy S26 Ultra",
    storage: "256GB",
    color: "Titanium Gray",
    condition: "New",
    price: 5299,
    image: "",
    description: "S Pen included. 200MP camera, Snapdragon 8 Elite, 6.9\" AMOLED display.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ss26u-512-tb",
    name: "Galaxy S26 Ultra",
    brand: "Samsung",
    model: "Galaxy S26 Ultra",
    storage: "512GB",
    color: "Titanium Black",
    condition: "New",
    price: 6099,
    image: "",
    description: "S Pen included. 200MP camera, Snapdragon 8 Elite, 6.9\" AMOLED display.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ss25u-256-used",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    model: "Galaxy S25 Ultra",
    storage: "256GB",
    color: "Titanium Blue",
    condition: "Used",
    price: 3899,
    image: "",
    description: "Like new condition. The ultimate Android experience with Galaxy AI.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "px9pro-256-ob",
    name: "Pixel 9 Pro XL",
    brand: "Google",
    model: "Pixel 9 Pro XL",
    storage: "256GB",
    color: "Obsidian",
    condition: "New",
    price: 3799,
    image: "",
    description: "Google's most powerful phone. Best Android camera, 7 years of updates.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "px9-128-po",
    name: "Pixel 9",
    brand: "Google",
    model: "Pixel 9",
    storage: "128GB",
    color: "Porcelain",
    condition: "New",
    price: 2799,
    image: "",
    description: "Pure Google experience. Tensor G4, exceptional cameras, AI-powered features.",
    inStock: true,
    createdAt: new Date().toISOString(),
  },
];
